var storeCards = [
  {
    id: 1,
    name: "Marie Curie",
    life: "68",
    attack: "100",
    defence: "40",
    price: 12.33,
    url: "img/cards/marieCurie.jpg",
  },
  {
    id: 2,
    name: "Albert Einstein",
    life: "76",
    attack: "78",
    defence: "99",
    price: 99.33,
    url: "img/cards/albertEinstein.jpg",
  },
  {
    id: 3,
    name: "Isaac Newton",
    life: "53",
    attack: "72",
    defence: "33",
    price: 34.33,
    url: "img/cards/isaacNewton.jpg",
  },
  {
    id: 4,
    name: "Nikola Tesla",
    life: "87",
    attack: "98",
    defence: "23",
    price: 98.33,
    url: "img/cards/nikolaTesla.jpeg",
  },
  {
    id: 5,
    name: "Stephen Hawking",
    life: "76",
    attack: "22",
    defence: "30",
    price: 119.33,
    url: "img/cards/stephenHawking.jpg",
  },
  {
    id: 6,
    name: "Galileo Galilei",
    life: "87",
    attack: "98",
    defence: "23",
    price: 98.33,
    url: "img/cards/galileoGalilei.jpg",
  },
  {
    id: 7,
    name: "Alan Turing",
    life: "41",
    attack: "55",
    defence: "30",
    price: 98.33,
    url: "img/cards/alanTuring.jpg",
  },
  {
    id: 8,
    name: "Noam Chomsky",
    life: "92",
    attack: "87",
    defence: "21",
    price: 1987.33,
    url: "img/cards/noamChomsky.jpg",
  },
];
